apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-bg
  namespace: nginx
  labels:
    name: nginx-bg
spec:
  project: default
  sources:
  - repoURL: 'https://akshay-cognologix.github.io/helm-charts/charts'
    chart: nginx-bg
    targetRevision: 1.0.0
    helm:
      valueFiles:
      - $values/values/nginx-bg/values-dev.yaml
  - repoURL: 'https://github.com/akshay-cognologix/sample-nginx.git'
    targetRevision: valuesyaml
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx